TestSuite[
	{
		"TensorCaching.mt",
		"CommonTensors.mt",
		"TensorCurves.mt",
		"TensorCreationAndCommonFunctionsTest.wrt",
		"TensorCreation.mt",
		"TensorManipulation.mt",
		"TensorDerivatives.mt"
		}]